import Head from "next/head";
import Dashboard from "components/user/Dashboard";
import SearchBar from "components/search/SearchBar";
import SignUp from "components/user/SignUp";
export default function NewUser() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SignUp />
    </>
  );
}
