import Head from "next/head";
import ResetPassword from "components/user/ResetPassword";
import ResetPasswordEmail from "components/user/ResetPasswordEmail";
import VerifyEmail from "components/user/VerifyEmail";
import { useRouter } from "next/router";

export default function Passwordreset() {
  const router = useRouter();
  console.log(router.query)
   return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {router.query.type == "enterEmail" ? (
        <ResetPasswordEmail />
      ) : router.query.type == "sentEmail" ? (
        <VerifyEmail />
      ) : (
        <ResetPassword token={router.query.token} />
      )}
    </>
  );
}
