import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import MainPage from 'components/mainPage/MainPage'
import SearchBar from 'components/search/SearchBar'
import BuyLeadd from 'components/buyLead/BuyLead'

const inter = Inter({ subsets: ['latin'] })

export default function BuyLead() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <SearchBar />
        <BuyLeadd />
      </main>
    </>
  )
}
